require("rinqtf.spec")
require("rinqtf.core")
spec("rinqtf.plugins.colorscheme")
spec("rinqtf.plugins.dressing")
spec("rinqtf.plugins.devicons")
spec("rinqtf.plugins.treesitter")
spec("rinqtf.plugins.mason")
require("rinqtf.lazy")
